### PR TITLE
Add Tests and CI

### PR DESCRIPTION
**Pull request by aisopuro**
This PR aims to add the baseline for unit tests, and automation to run those tests on changes. It also does a small consolidation of where the version number is defined and how it is exposed.

The first test is a trivial test, but is enough to have something to run in the CI. The run also gathers coverage, though this does not fail the job if it fails.

Currently the CI fails for all Python versions on Mac. The first version of the tests during development succeeded, and then suddenly all of them failed. It is unknown why this is.

It seems to me there are 2 different things we can do:
1. State that tests don't need to be run againsta Mac and remove it from the test matrix
2. Have someone with a Mac look into whether they can reproduce and fix the problem

### CODE REVIEW

**Comment by aisopuro** [comment]
I suppose one possibility might be to figure out some kind of test run that works on `macos` and split that into a separate workflow or something, but I'm a little hesitant to split the testing infrastructure in two like that.

**Comment by hegenator** [comment]
I agree, splitting is probably not a good idea

**Comment by hegenator** [comment]
I added some things I had been working on in the `dev` branch, and also rebased on `master`, so this seems to also be in need of a rebase now.

I will have to try and configure the CI on the repo to get it running, but seems good.

**Comment by aisopuro** [comment]
I made a new branch with all the rebases etc. This PR is replaced by #7

**Pull request closed without merging**
